name: Client deployment workflow
on:
  push:
    branches:
      - main
env:
  CI: false
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Development Code
        uses: actions/checkout@v2
      - name: Use Node.js 19.x
        uses: actions/setup-node@v1
        with:
          node-version: 19.x
      - name: npm install, build
        run: |
          npm install
          npm run build --if-present
        working-directory: client
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
